football/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'premierleagues/new'

  get 'premierleagues/create'

  get 'premierleagues/update'

  get 'premierleagues/edit'

  get 'premierleagues/destroy'

  get 'premierleagues/index'

  get 'premierleagues/show'

  get 'pitches/new'

  get 'pitches/create'

  get 'pitches/update'

  get 'pitches/edit'

  get 'pitches/destroy'

  get 'pitches/index'

  get 'pitches/show'

  get 'sponsors/new'

  get 'sponsors/create'

  get 'sponsors/update'

  get 'sponsors/edit'

  get 'sponsors/destroy'

  get 'sponsors/index'

  get 'sponsors/show'

  get 'coaches/new'

  get 'coaches/create'

  get 'coaches/update'

  get 'coaches/edit'

  get 'coaches/destroy'

  get 'coaches/index'

  get 'coaches/show'

  get 'soccers/new'

  get 'soccers/create'

  get 'soccers/update'

  get 'soccers/edit'

  get 'soccers/destroy'

  get 'soccers/index'

  get 'soccers/show'

  get 'about/index'

  root 'soccers#index'

  get 'about' => 'about#index'

  resources :soccers
  resources :coaches
  resources :sponsors
  resources :pitches
  resources :premierleagues

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

football/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

football/app/models/coach.rb
class Coach < ApplicationRecord
		has_many :soccers

		validates :last_name, presence: true,length: { minimum: 5 },uniqueness: {case_sensitive: false}
end

football/app/models/pitch.rb
class Pitch < ApplicationRecord
	has_many :soccers

	validates :name, presence: true,length: { minimum: 2 },uniqueness: {case_sensitive: false}
end

football/app/models/soccer.rb
class Soccer < ApplicationRecord
	belongs_to :coach
	belongs_to :pitch
	belongs_to :sponsor
end

football/app/models/sponsor.rb
class Sponsor < ApplicationRecord
	has_many :soccers

	validates :name, presence: true,length: { minimum: 2 },uniqueness: {case_sensitive: false}
end

football/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

football/app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  	@page_title = 'About us';
  end
end

football/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
before_action :authenticate_user!, :except => [:search]

     def authenticate_user
    redirect_to new_user_registration_url unless user_signed_in?
  end
end

football/app/controllers/coaches_controller.rb
class CoachesController < ApplicationController
  def new
    @page_title='Add New Coach'
    @coach = Coach.new
  end

  def create
    @coach = Coach.new(coach_prams)
    if @coach.save
      flash[:notice] = "Coach Created"

      redirect_to coaches_path
    else
      render 'new'
    end
  end

  def update
    @coach = Coach.find(params[:id])
    if @coach.update(coach_prams)

    flash[:notice] = 'Coach Updated'

    redirect_to coaches_path
  else 
          render 'new'
  end
  end

  def edit
    @coach = Coach.find(params[:id])
  end

  def destroy
    @coach = Coach.find(params[:id])
    @coach.destroy

    flash[:notice] = 'Coach Removed'

    redirect_to coaches_path
  end

  def index
    @coaches = Coach.all
  end

  def show
    @coach = Coach.find(params[:id])
    @coaches = Coach.all
    @soccers = @coach.soccers
  end

  private
    def coach_prams
      params.require(:coach).permit(:first_name, :last_name)
    end
end

football/app/controllers/pitches_controller.rb
class PitchesController < ApplicationController
  def new
    @page_title='Add New Stadium'
    @pitch = Pitch.new
  end

  def create
    @pitch = Pitch.new(pitch_prams)
    if @pitch.save
      flash[:notice] = "Stadium Created"

      redirect_to pitches_path
    else
      render 'new'
    end
  end

  def update
    @pitch = Pitch.find(params[:id])
    @pitch.update(pitch_prams)

    flash[:notice] = 'Stadium Updated'

    redirect_to pitches_path
  end

  def edit
    @pitch = Pitch.find(params[:id])
  end

  def destroy
    @pitch = Pitch.find(params[:id])
    @pitch.destroy

    flash[:notice] = 'Stadium Removed'

    redirect_to pitches_path
  end

  def index
    @pitches = Pitch.all
  end

  def show
    @pitch = Pitch.find(params[:id])
    @pitches = Pitch.all
    @soccers = @pitch.soccers
  end

  private
    def pitch_prams
      params.require(:pitch).permit(:name)
    end
end

football/app/controllers/soccers_controller.rb
class SoccersController < ApplicationController
  def new
    @page_title = 'Add New Team'
    @soccer = Soccer.new
    @coach = Coach.new
    @sponsor = Sponsor.new
    @pitch = Pitch.new
  end

  def create
    @soccer = Soccer.new(soccer_prams)
    if @soccer.save
    flash[:notice] = 'Team Added'

    redirect_to soccers_path
  else
    render'new'
  end
  end

  def update
    @soccer = Soccer.find(params[:id])
    @soccer.update(soccer_prams)

    flash[:notice] = 'Team Updated'

    redirect_to soccers_path
  end

  def edit
    @soccer = Soccer.find(params[:id])
  end

  def destroy
    @soccer = Soccer.find(params[:id])
    @soccer.destroy

    flash[:notice] = 'Team Removed'

    redirect_to soccers_path
  end

  def index
    @soccers = Soccer.all
   end

  def show
    @soccer = Soccer.find(params[:id])
  end

  private
    def soccer_prams
      params.require(:soccer).permit(:title, :coach_id, :pitch_id, :sponsor_id, :founded, :trophy, :coverpath, :excerpt, :nation, :owner, :visit)
    end
end

football/app/controllers/sponsors_controller.rb
class SponsorsController < ApplicationController
  def new
    @page_title='Add New Sponsor'
    @sponsor = Sponsor.new
  end

  def create
    @sponsor = Sponsor.new(sponsor_prams)
    if @sponsor.save
      flash[:notice] = "Sponsor Created"

      redirect_to sponsors_path
    else
      render 'new'
    end
  end

  def update
    @sponsor = Sponsor.find(params[:id])
    @sponsor.update(sponsor_prams)

    flash[:notice] = 'Sponsor Updated'

    redirect_to sponsors_path
  end

  def edit
    @sponsor = Sponsor.find(params[:id])
  end

  def destroy
    @sponsor = Sponsor.find(params[:id])
    @sponsor.destroy

    flash[:notice] = 'Sponsor Removed'

    redirect_to sponsors_path
  end

  def index
    @sponsors = Sponsor.all
  end

  def show
    @sponsor = Sponsor.find(params[:id])
    @sponors = Sponsor.all
    @soccers = @sponsor.soccers
  end

  private
    def sponsor_prams
      params.require(:sponsor).permit(:name)
    end
end

football/app/helpers/about_helper.rb
module AboutHelper
end

football/app/helpers/application_helper.rb
module ApplicationHelper
end

football/app/helpers/coaches_helper.rb
module CoachesHelper
end

football/app/helpers/pitches_helper.rb
module PitchesHelper
end

football/app/helpers/soccers_helper.rb
module SoccersHelper
end

football/app/helpers/sponsors_helper.rb
module SponsorsHelper
end

football/app/views/about/index.html.erb
<h1><%f= @page_title %></h1>
<p>F Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc mattis in mauris nec finibus. Praesent consectetur quam non massa condimentum eleifend. Duis aliquet blandit auctor. Morbi maximus odio vel consectetur condimentum. Integer fermentum felis a luctus tincidunt. Morbi id nisl aliquet, sollicitudin dolor vehicula, mattis ligula. Etiam elementum ligula massa, a hendrerit tortor eleifend a. Vestibulum et nisl vel ex placerat molestie. Nunc efficitur velit et faucibus gravida.

Nunc ullamcorper sed libero sed dictum. Ut laoreet blandit hendrerit. Mauris enim libero, auctor at vulputate id, semper accumsan nulla. Fusce interdum, mauris eget ornare fermentum, sem elit malesuada dui, hendrerit sagittis purus mauris vitae metus. Vivamus a lectus vitae sapien facilisis porttitor nec eu justo. Phasellus ornare magna ipsum, quis malesuada neque efficitur et. Sed ex arcu, mattis vel tincidunt id, finibus id nulla. Aenean finibus lorem vel sem finibus convallis. Quisque condimentum, purus eget gravida malesuada, nunc magna maximus dui, vitae finibus enim nunc vel enim. Etiam eget pharetra neque. Nulla ac consequat orci, sit amet scelerisque augue. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Donec mollis nunc a feugiat scelerisque. </p>

football/app/views/coaches/create.html.erb
<h1>Coaches#create</h1>
<p>Find me in app/views/coaches/create.html.erb</p>

football/app/views/coaches/destroy.html.erb
<h1>Coaches#destroy</h1>
<p>Find me in app/views/coaches/destroy.html.erb</p>

football/app/views/coaches/edit.html.erb
<h3>Edit Coach</h3>
<%= form_for @coach do |f| %>
	<% if @coach.errors.any? %>
		<% @coach.errors.full_messages.each do |msg| %>
			<div class="alert alert-danger"><%= msg %></div>
		<% end %>
	<% end %>

	<div class="form-group">
		<%= f.label :first_name %><br />
		<%= f.text_field :first_name, class:'form-control' %><br />
	</div>

	<div class="form-group">
		<%= f.label :last_name %><br />
		<%= f.text_field :last_name, class:'form-control' %><br />
	</div>

	<%= f.submit "Submit", class:'btn btn-primary' %>
	<%= link_to "Cancel", coaches_path, class:'btn btn-default' %>
<% end %> 

football/app/views/coaches/index.html.erb
<h2>Coaches</h2>

<table class="table table-striped">
	<tr>
		<th>Coach Name</th>
		<th>Actions</th>
	</tr>

<% @coaches.each do |coach|%>
	<tr>
		<td><%= coach.first_name %> <%= coach.last_name %></td>
		<td><%= link_to 'Edit', edit_coach_path(coach.id) %> | <%= link_to 'Delete', coach_path(coach), method: :delete, data: {confirm: 'Are you sure?'} %></td>
	</tr>
	<% end %>
</table>

football/app/views/coaches/new.html.erb
<h3>Add New Coach</h3>
<%= form_for @coach do |f| %>
	<% if @coach.errors.any? %>
		<% @coach.errors.full_messages.each do |msg| %>
			<div class="alert alert-danger"><%= msg %></div>
		<% end %>
	<% end %>

	<div class="form-group">
		<%= f.label :first_name %><br />
		<%= f.text_field :first_name, class:'form-control' %><br />
	</div>

	<div class="form-group">
		<%= f.label :last_name %><br />
		<%= f.text_field :last_name, class:'form-control' %><br />
	</div>

	<%= f.submit "Submit", class:'btn btn-primary' %>
	<%= link_to "Cancel", coaches_path, class:'btn btn-default' %>
<% end %> 

football/app/views/coaches/show.html.erb
<h1>Coaches#show</h1>
<p>Find me in app/views/coaches/show.html.erb</p>

football/app/views/coaches/update.html.erb
<h1>Coaches#update</h1>
<p>Find me in app/views/coaches/update.html.erb</p>

football/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= @page_title ? @page_title : 'Welcome'%> | Football</title>
    <%= csrf_meta_tags %>
	<meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

   <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" >INFORMATION</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li class="active"><%= link_to 'Home', root_path%></li>
            <li><%= link_to 'About', about_path%></li>
          </ul>

        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to 'Sign up', new_user_registration_path %></li>
          <li><%= link_to 'Sign in', new_user_session_path %></li>
          <li><%= link_to 'Sign out', destroy_user_session_path, method: :delete %></li>
        </ul>

          <ul class="nav navbar-nav navbar-right">
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Add New <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to 'Team', new_soccer_path%></li>
                <li><%= link_to 'Stadium', new_pitch_path%></li>
                <li><%= link_to 'Sponsor', new_sponsor_path%></li>
                <li><%= link_to 'Coach', new_coach_path%></li>
              </ul>
            </li>
          </ul>

          <ul class="nav navbar-nav navbar-right">
              <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Manage <span class="caret"></span></a>
          <ul class="dropdown-menu ">
            <li><%= link_to 'Coach', coaches_path%></li>
            <li><%= link_to 'Stadium', pitches_path%></li>
            <li><%= link_to 'Sponsor', sponsors_path%></li>
          </ul>
        </li>
        </ul>



        </div><!--/.nav-collapse -->
      </div>
    </nav>

	<header>
		<div class="container">
			<h1>Football <small> <%= @page_title ? @page_title : 'Welcome'%></small></h1>
		</div>
	</header>

    <section>
    	<div class = "container">
    		<div class="row">
    			<div class="col-md-8">
          <% if flash[:notice] %>
            <div class = "alert alert-success"><%= flash[:notice] %></div>
          <% end %>

          <% if flash[:alert] %>
            <div class = "alert alert-danger"><%= flash[:alert] %></div>
          <% end %>

    				<%= yield %>

    			</div>
    			<div class="col-md-4">
    				<%= render 'partials/sidebar' %>
    			</div>
    		</div>
    	</div>
	</section>

	<footer>
		<div class="container">
			<p>Copyright &copy; 2017, All Rights Resrved</p>
		</div>
	</footer>
  </body>
</html>

football/app/views/partials/_sidebar.html.erb
<% if params[:controller] == 'about' %>
<div class= "well">
	<h3>Location Info</h3>
	<ul>
		<li>The Bookstore</li>
		<li>499 Massachusets Avenue, Unit 2</li>
		<li>London, MA 02889</li>
		<li>Phone: (617) 666.6666</li>
		<li>Email: supporter@thebookstore.com</li>
	</ul>
</div>
<% end %>

football/app/views/pitches/create.html.erb
<h1>Pitches#create</h1>
<p>Find me in app/views/pitches/create.html.erb</p>

football/app/views/pitches/destroy.html.erb
<h1>Pitches#destroy</h1>
<p>Find me in app/views/pitches/destroy.html.erb</p>

football/app/views/pitches/edit.html.erb
<h3>Edit Stadium</h3>
<%= form_for @pitch do |f| %>
	<% if @pitch.errors.any? %>
		<% @pitch.errors.full_messages.each do |msg| %>
			<div class="alert alert-danger"><%= msg %></div>
		<% end %>
	<% end %>

	<div class="form-group">
		<%= f.label :name %><br />
		<%= f.text_field :name, class:'form-control' %><br />
	</div>

	<%= f.submit "Submit", class:'btn btn-primary' %>
	<%= link_to "Cancel", pitches_path, class:'btn btn-default' %>
<% end %>

football/app/views/pitches/index.html.erb
<h2>Stadiums</h2>

<table class="table table-striped">
	<tr>
		<th>Stadium Name</th>
		<th>Actions</th>
	</tr>

<% @pitches.each do |pitch|%>
	<tr>
		<td><%= pitch.name %></td>
		<td><%= link_to 'Edit', edit_pitch_path(pitch.id) %> | <%= link_to 'Delete', pitch_path(pitch), method: :delete, data: {confirm: 'Are you sure?'} %></td>
	</tr>
	<% end %>
</table>

football/app/views/pitches/new.html.erb
<h3>Add New Stadium</h3>
<%= form_for @pitch do |f| %>
	<% if @pitch.errors.any? %>
		<% @pitch.errors.full_messages.each do |msg| %>
			<div class="alert alert-danger"><%= msg %></div>
		<% end %>
	<% end %>

	<div class="form-group">
		<%= f.label :name %><br />
		<%= f.text_field :name, class:'form-control' %><br />
	</div>

	<%= f.submit "Submit", class:'btn btn-primary' %>
	<%= link_to "Cancel", pitches_path, class:'btn btn-default' %>
<% end %>

football/app/views/pitches/show.html.erb
<h1>Pitches#show</h1>
<p>Find me in app/views/pitches/show.html.erb</p>

football/app/views/pitches/update.html.erb
<h1>Pitches#update</h1>
<p>Find me in app/views/pitches/update.html.erb</p>

football/app/views/soccers/create.html.erb
<h1>Soccers#create</h1>
<p>Find me in app/views/soccers/create.html.erb</p>

football/app/views/soccers/destroy.html.erb
<h1>Soccers#destroy</h1>
<p>Find me in app/views/soccers/destroy.html.erb</p>

football/app/views/soccers/edit.html.erb
<h3>Edit Team</h3>
<%= form_for @soccer do |f| %>
	<div class="form-group">
		<%= f.label :Name %><br />
		<%= f.text_field :title, class:'form-control' %><br />
	</div>

	<div class="form-group">
		<%= f.label :Stadium %><br />
		<%= f.select :pitch_id, Pitch.all.collect {|x| [x.name, x.id]},{:include_blank => 'Select One'},class:'form-control' %><br /><br />
	</div>

	<div class="form-group">
		<%= f.label :Coach%><br />
		<%= f.select :coach_id, Coach.all.collect {|x| [x.first_name + '' + x.last_name, x.id]},{:include_blank => 'Select One'},class:'form-control' %><br /><br />
	</div>

	<div class="form-group">
		<%= f.label :Sponsor %><br />
		<%= f.select :sponsor_id, Sponsor.all.collect {|x| [x.name, x.id]},{:include_blank => 'Select One'},class:'form-control' %><br /><br />
	</div>

	<div class="form-group">
		<%= f.label :Founded %><br />
		<%= f.text_field :founded, class:'form-control' %><br />
	</div>

	<div class="form-group">
		<%= f.label :Trophy %><br />
		<%= f.text_field :trophy, class:'form-control' %><br />
	</div>

	<div class="form-group">
		<%= f.label :Path %><br />
		<%= f.text_field :coverpath, class:'form-control' %><br />
	</div>

	<div class="form-group">
		<%= f.label :Excerpt %><br />
		<%= f.text_field :excerpt, class:'form-control' %><br />
	</div>

	<div class="form-group">
		<%= f.label :Owner %><br />
		<%= f.text_field :owner, class:'form-control' %><br />
	</div>

	<div class="form-group">
		<%= f.label :Visit %><br />
		<%= f.text_field :visit, class:'form-control' %><br />
	</div>

	<%= f.submit "Submit", class:'btn btn-primary' %>
	<%= link_to "Cancel", soccers_path, class:'btn btn-default' %>
<% end %>

football/app/views/soccers/index.html.erb
<div id="soccers-index">
	<% @soccers.each_slice(100) do |soccer| %>
		<div class="row" >
			<% @soccers.each do |soccer| %>
				<div class="col-md-4 col-sm-3">
				<h3><%= soccer.title %></h3>
				<%= image_tag(soccer.coverpath) %>
				<%= link_to 'Read more', soccer_path(soccer),class:'btn btn-primary' %>
				</div>
			<% end %>
		</div>
	<% end %>
</div>

football/app/views/soccers/new.html.erb
<h3>Add New Team</h3>
<%= form_for @soccer do |f| %>
	<div class="form-group">
		<%= f.label :Name %><br />
		<%= f.text_field :title, class:'form-control' %><br />
	</div>

	<div class="form-group">
		<%= f.label :Nation %><br />
		<%= f.text_field :nation, class:'form-control' %><br />
	</div>

	<div class="form-group">
		<%= f.label :Stadium %><br />
		<%= f.select :pitch_id, Pitch.all.collect {|x| [x.name, x.id]},{:include_blank => 'Select One'},class:'form-control' %><br /><br />
	</div>

	<div class="form-group">
		<%= f.label :Coach%><br />
		<%= f.select :coach_id, Coach.all.collect {|x| [x.first_name + '' + x.last_name, x.id]},{:include_blank => 'Select One'},class:'form-control' %><br /><br />
	</div>

	<div class="form-group">
		<%= f.label :Sponsor %><br />
		<%= f.select :sponsor_id, Sponsor.all.collect {|x| [x.name, x.id]},{:include_blank => 'Select One'},class:'form-control' %><br /><br />
	</div>

	<div class="form-group">
		<%= f.label :Founded %><br />
		<%= f.text_field :founded, class:'form-control' %><br />
	</div>

	<div class="form-group">
		<%= f.label :Trophy %><br />
		<%= f.text_field :trophy, class:'form-control' %><br />
	</div>

	<div class="form-group">
		<%= f.label :Path %><br />
		<%= f.text_field :coverpath, class:'form-control' %><br />
	</div>

	<div class="form-group">
		<%= f.label :Excerpt %><br />
		<%= f.text_field :excerpt, class:'form-control' %><br />
	</div>

	<div class="form-group">
		<%= f.label :Owner %><br />
		<%= f.text_field :owner, class:'form-control' %><br />
	</div>

	<div class="form-group">
		<%= f.label :Visit %><br />
		<%= f.text_field :visit, class:'form-control' %><br />
	</div>

	<%= f.submit "Submit", class:'btn btn-primary' %>
	<%= link_to "Cancel", soccers_path, class:'btn btn-default' %>
<% end %>

football/app/views/soccers/show.html.erb
<div id="soccers-show">
	<h2><%= @soccer.title %></h2>
	<div class="soccer-show-left">
		<%= image_tag(@soccer.coverpath) %>
	</div>
	<div class="soccer-show-right">
		<h3>Football info:</h3>
		<ul>
			<li><strong>Stadium:</strong> <%= @soccer.pitch.name %>/</li>
			<li><strong>Coach:</strong> <%= @soccer.coach.first_name %> <%= @soccer.coach.last_name %>/</li>
			<li><strong>Sponsor:</strong> <%= @soccer.sponsor.name %>/</li>
			<li><strong>Founded:</strong> <%= @soccer.founded %>/</li>
			<li><strong>Trophy:</strong> <%= @soccer.trophy %>/</li>
			<li><strong>Owner:</strong> <%= @soccer.owner %>/</li>
			<li><strong>nation:</strong> <%= @soccer.nation %>/</li>

		</ul>
		<%= link_to "Visit us" ,@soccer.visit,class:'btn btn-success',target:'_blank' %>
	</div>
	<div class="clearfix"></div>
	<h4>Expert</h4>
	<p><%= @soccer.excerpt %>/ </p>

	<%= link_to 'Edit', edit_soccer_path(@soccer.id) %> | <%= link_to 'Delete', soccer_path(@soccer), method: :delete, data: {confirm: 'Are you sure?'} %>

</div>

football/app/views/soccers/update.html.erb
<h1>Soccers#update</h1>
<p>Find me in app/views/soccers/update.html.erb</p>

football/app/views/sponsors/create.html.erb
<h1>Sponsors#create</h1>
<p>Find me in app/views/sponsors/create.html.erb</p>

football/app/views/sponsors/destroy.html.erb
<h1>Sponsors#destroy</h1>
<p>Find me in app/views/sponsors/destroy.html.erb</p>

football/app/views/sponsors/edit.html.erb
<h3>Edit Sponsor</h3>
<%= form_for @sponsor do |f| %>
	<% if @sponsor.errors.any? %>
		<% @sponsor.errors.full_messages.each do |msg| %>
			<div class="alert alert-danger"><%= msg %></div>
		<% end %>
	<% end %>
	<div class="form-group">
		<%= f.label :name %><br />
		<%= f.text_field :name, class:'form-control' %><br />
	</div>

	<%= f.submit "Submit", class:'btn btn-primary' %>
	<%= link_to "Cancel", sponsors_path, class:'btn btn-default' %>
<% end %>

football/app/views/sponsors/index.html.erb
<h2>Sponsors</h2>

<table class="table table-striped">
	<tr>
		<th>Sponsor Name</th>
		<th>Actions</th>
	</tr>

<% @sponsors.each do |sponsor|%>
	<tr>
		<td><%= sponsor.name %></td>
		<td><%= link_to 'Edit', edit_sponsor_path(sponsor.id) %> | <%= link_to 'Delete', sponsor_path(sponsor), method: :delete, data: {confirm: 'Are you sure?'} %></td>
	</tr>
	<% end %>
</table>

football/app/views/sponsors/new.html.erb
<h3>Add New Sponsor</h3>
<%= form_for @sponsor do |f| %>
	<% if @sponsor.errors.any? %>
		<% @sponsor.errors.full_messages.each do |msg| %>
			<div class="alert alert-danger"><%= msg %></div>
		<% end %>
	<% end %>
	<div class="form-group">
		<%= f.label :name %><br />
		<%= f.text_field :name, class:'form-control' %><br />
	</div>

	<%= f.submit "Submit", class:'btn btn-primary' %>
	<%= link_to "Cancel", sponsors_path, class:'btn btn-default' %>
<% end %>

football/app/views/sponsors/show.html.erb
<h1>Sponsors#show</h1>
<p>Find me in app/views/sponsors/show.html.erb</p>

football/app/views/sponsors/update.html.erb
<h1>Sponsors#update</h1>
<p>Find me in app/views/sponsors/update.html.erb</p>